# Lecture 17: Manipulating data

- Questions?
- How was the lab? üëç/üëé

- [Project due dates](https://computing-in-context.afeld.me/#schedule) adjusted
- Will introduce [Project 1](https://computing-in-context.afeld.me/project_1.html) at the end

## Today's goal

- Which 311 complaints are most common?
- Which agencies are responsible for handling them?

## Read our cleaned 311 Service Requests dataset

In [1]:
import pandas as pd

url = "https://storage.googleapis.com/python-public-policy2/data/311_requests_2018-19_sample_clean.csv.zip"
df_cleaned = pd.read_csv(url)

/var/folders/kr/nx0m1j811kz5vy8c87ffchzr0000gn/T/ipykernel_33341/239018350.py:4: DtypeWarning: Columns (8,20,31,34) have mixed types. Specify dtype option on import or set low_memory=False.
  df_cleaned = pd.read_csv(url)

## Which 311 complaints are most common and which agencies are responsible for handling them?

#### Which complaints are the most common?

In [2]:
df_cleaned.groupby("Complaint Type").size().reset_index(name="count")

                    Complaint Type  count
0                        APPLIANCE   2539
1                Abandoned Vehicle   1655
2                 Advocate - Other     26
3    Advocate-Co-opCondo Abatement      4
4     Advocate-Personal Exemptions     24
..                             ...    ...
208                     WATER LEAK   6641
209             Water Conservation    853
210                  Water Quality    332
211                   Water System  12949
212                   Window Guard      6

[213 rows x 2 columns]

`.reset_index(name='count')` isn't necessary, but it's helpful to include because it allows us to name the new column that contains the count of rows.

#### Which agencies are responsible for handling these complaint categories?

In [3]:
df_cleaned.groupby(["Agency", "Complaint Type"]).size().reset_index(name="count")

    Agency                             Complaint Type  count
0      ACS                                      Forms     56
1     COIB                                      Forms      1
2      DCA                         Consumer Complaint   2892
3      DCA  DCA / DOH New License Application Request    186
4     DCAS                                   Comments     13
..     ...                                        ...    ...
216    TLC                              Lost Property    472
217    TLC                             Taxi Complaint   2416
218    TLC                            Taxi Compliment     41
219    TLC                    Taxi Licensee Complaint      5
220    TLC                                Taxi Report    318

[221 rows x 3 columns]

#### Which agencies receive the most total 311 requests?

In [4]:
df_cleaned.groupby("Agency").size().reset_index(name="count")

   Agency   count
0     ACS      56
1    COIB       1
2     DCA    3078
3    DCAS     149
4     DCP       4
5     DEP   36283
6    DFTA    1182
7     DHS    3670
8     DOB   26024
9     DOE     442
10    DOF    7223
11  DOHMH   12690
12  DOITT     115
13    DOT   52001
14    DPR   21086
15   DSNY   73227
16    EDC     303
17    HPD  105634
18    HRA    1649
19  NYCEM      25
20   NYPD  148884
21    TAT       1
22    TAX      37
23    TLC    6194

#### What is the most frequent request per agency?

First, create a dataframe that contains the count of complaints per `Agency` per `Complaint Type`.

In [5]:
agency_counts = df_cleaned.groupby(["Agency", "Complaint Type"]).size().reset_index(name="count")
agency_counts.head(20)

   Agency                             Complaint Type  count
0     ACS                                      Forms     56
1    COIB                                      Forms      1
2     DCA                         Consumer Complaint   2892
3     DCA  DCA / DOH New License Application Request    186
4    DCAS                                   Comments     13
5    DCAS                                   Question    136
6     DCP                         Research Questions      4
7     DEP                                Air Quality   1457
8     DEP                                   Asbestos    316
9     DEP                                       FATF     23
10    DEP                        Hazardous Materials    549
11    DEP                           Industrial Waste    263
12    DEP                                       Lead   1825
13    DEP                                      Noise  10937
14    DEP                                      Plant     22
15    DEP                                      Sewer   6757
16    DEP                         Water Conservation    853
17    DEP                              Water Quality    332
18    DEP                               Water System  12949
19   DFTA                           Alzheimer's Care     25

Use `drop_duplicates()` to keep the row with the highest value per `Agency`.

In [6]:
sorted_agency_counts = agency_counts.sort_values("count", ascending=False)
sorted_agency_counts

    Agency                       Complaint Type  count
198   NYPD                  Noise - Residential  41311
169    HPD                       HEAT/HOT WATER  39095
194   NYPD                      Illegal Parking  34297
154   DSNY  Request Large Bulky Item Collection  30939
186   NYPD                     Blocked Driveway  25530
..     ...                                  ...    ...
119    DOT              Highway Sign - Dangling      3
94   DOHMH                 Radioactive Material      3
139    DPR                 Unsanitary Condition      1
207    TAT                             Question      1
1     COIB                                Forms      1

[221 rows x 3 columns]

In [7]:
top_agency_counts = sorted_agency_counts.drop_duplicates("Agency")
top_agency_counts

    Agency                       Complaint Type  count
198   NYPD                  Noise - Residential  41311
169    HPD                       HEAT/HOT WATER  39095
154   DSNY  Request Large Bulky Item Collection  30939
124    DOT                     Street Condition  16895
18     DEP                         Water System  12949
42     DOB        General Construction/Plumbing   9537
95   DOHMH                               Rodent   6253
132    DPR                         Damaged Tree   6065
29     DHS           Homeless Person Assistance   3670
2      DCA                   Consumer Complaint   2892
212    TLC           For Hire Vehicle Complaint   2789
67     DOF       DOF Property - Reduction Issue   1846
180    HRA             Benefit Card Replacement   1649
25    DFTA          Housing - Low Income Senior    768
53     DOE                   School Maintenance    442
161    EDC                   Noise - Helicopter    303
5     DCAS                             Question    136
106  DOITT            Public Payphone Complaint     75
0      ACS                                Forms     56
209    TAX                             Question     34
181  NYCEM               OEM Literature Request     25
6      DCP                   Research Questions      4
207    TAT                             Question      1
1     COIB                                Forms      1

For nicer display, order alphabetically:

In [8]:
top_agency_counts.sort_values("Agency")

    Agency                       Complaint Type  count
0      ACS                                Forms     56
1     COIB                                Forms      1
2      DCA                   Consumer Complaint   2892
5     DCAS                             Question    136
6      DCP                   Research Questions      4
18     DEP                         Water System  12949
25    DFTA          Housing - Low Income Senior    768
29     DHS           Homeless Person Assistance   3670
42     DOB        General Construction/Plumbing   9537
53     DOE                   School Maintenance    442
67     DOF       DOF Property - Reduction Issue   1846
95   DOHMH                               Rodent   6253
106  DOITT            Public Payphone Complaint     75
124    DOT                     Street Condition  16895
132    DPR                         Damaged Tree   6065
154   DSNY  Request Large Bulky Item Collection  30939
161    EDC                   Noise - Helicopter    303
169    HPD                       HEAT/HOT WATER  39095
180    HRA             Benefit Card Replacement   1649
181  NYCEM               OEM Literature Request     25
198   NYPD                  Noise - Residential  41311
207    TAT                             Question      1
209    TAX                             Question     34
212    TLC           For Hire Vehicle Complaint   2789

Another way, only sorting it once:

In [9]:
agency_counts.sort_values(['Agency', 'count'], ascending=False)

    Agency                             Complaint Type  count
212    TLC                 For Hire Vehicle Complaint   2789
217    TLC                             Taxi Complaint   2416
216    TLC                              Lost Property    472
220    TLC                                Taxi Report    318
213    TLC                    For Hire Vehicle Report    112
..     ...                                        ...    ...
4     DCAS                                   Comments     13
2      DCA                         Consumer Complaint   2892
3      DCA  DCA / DOH New License Application Request    186
1     COIB                                      Forms      1
0      ACS                                      Forms     56

[221 rows x 3 columns]

## [Project 1](https://computing-in-context.afeld.me/project_1.html)

Can you see the rubric?